### ISSUE TITLE
builds fail due to shell setting

### ISSUE THREAD

**Issue by vxtra1973** [Rudd-O/shared-jenkins-libraries#1]
In the script updateBuildNumberDisplayName.groovy the use of /bin/sh [here](https://github.com/Rudd-O/shared-jenkins-libraries/blob/c520a539ba7b70303a97843a9e9ed54316d03cae/vars/updateBuildNumberDisplayName.groovy#L3) causes the build to fail because popd and pushd are bash functions that are not available in /bin/sh on debian 9

**Comment by Rudd-O** [comment]
Will fix.  Thank you so much.

**Comment by Rudd-O** [comment]
Fixed.  Please verify.

**Comment by Rudd-O** [comment]
(on `master`)
